---
title: "Project"
author: "Ananda Poudel"
date: "3/16/2021"
output: rmarkdown::github_document
---

# Libraries and setting directory.
```{r}
setwd("/Users/apoudel53/Desktop/Job Search/project")
#The data came in partitioned.
hrAnalytics <- read.csv("aug_train.csv")
library(caret)
library(dplyr)
library(ggplot2)
#library(corrplot)
library(caret)
library(vip)
library(ROCR)
```

# Exploratory data analysis.
#### Dealing with missing values.
```{r}
#Checking for na and blank values in each column for our data.

emptyValues <- sapply(colnames(hrAnalytics), function(x){
  sum(is.na(hrAnalytics[,x]) | hrAnalytics[,x] == '') 
})


#Set the threshold of missing values by averaging the number of mising values from the columns that contain those missing values.
emptyValues <- as.data.frame(emptyValues)
names(emptyValues)[1] <- "values"
emptyValues <- emptyValues %>%
  filter(values > 0)
avg <- mean(emptyValues$values)
removeEmptyValues <- emptyValues %>%
  filter(values < avg)
removeEmptyValues
# These variables will not consider the blank values since the number of blank values are below the mean so we'll remove the rows from the original dataset where the values were blank.

emptyValues <- emptyValues %>%
  filter(values > avg)
emptyValues
#These variables will consider the blank values as a factor. 


hrAnalytics <- hrAnalytics %>%
  filter(enrolled_university != '', education_level != '', experience != '', last_new_job != '')

#Checking to make sure there are no empty values for the specified columns
sapply(c("enrolled_university", "education_level", "experience", "last_new_job"), function(x){
  sum(is.na(hrAnalytics[,x]) | hrAnalytics[,x] == '')
})

```

#### Renaming variables and converting data types.
```{r}
hrAnalytics$gender[which(hrAnalytics$gender == '')] <- 'Not specified'
hrAnalytics$enrolled_university[which(hrAnalytics$enrolled_university == 'no_enrollment')] <- "Not enrolled"
hrAnalytics$major_discipline[which(hrAnalytics$major_discipline == '')] <- "Not specified"
hrAnalytics$experience[which(hrAnalytics$experience == '>20')] <- "More than 20"
hrAnalytics$experience[which(hrAnalytics$experience == '<1')] <- "Less than 1"
hrAnalytics$company_size[which(hrAnalytics$company_size == '')] <- "Not specified"
hrAnalytics$company_size[which(hrAnalytics$company_size == '<10')] <- "Less than 10"
hrAnalytics$company_size[which(hrAnalytics$company_size == '10/49')] <- "10-49"
hrAnalytics$company_size[which(hrAnalytics$company_size == '10000+')] <- "More than 10000"
hrAnalytics$company_type[which(hrAnalytics$company_type == '')] <- "Not specified"
hrAnalytics$company_type[which(hrAnalytics$company_type == 'Pvt Ltd')] <- "Private Limited"
hrAnalytics$last_new_job[which(hrAnalytics$last_new_job == '>4')] <- "Greater than 4"


str(hrAnalytics)
#Characters need to be turned into factor for it to be considered in the model.
hrAnalytics <- hrAnalytics %>% 
  mutate_if(sapply(hrAnalytics, is.character), as.factor)
str(hrAnalytics)

```

#### Data visualization and transformation.
```{r, fig.width=20, fig.height=10}
#Visualizing gender and job change.
hrAnalytics$jobChange <- "Looking for a job change"
hrAnalytics$jobChange[which(hrAnalytics$target == 0)] <- "Not looking for a job change"

ggplot(data = hrAnalytics, aes(x = gender, fill = jobChange)) + geom_bar(position = 'dodge') + xlab("Gender") +
  ylab("Job Changes Count") + ggtitle("Number of Job Changes Based on Gender") + 
  geom_text(stat = 'count', aes(label = ..count..), vjust = -1, position = position_dodge(0.9)) +
  labs(fill = "Job Change") +
  theme(plot.title = element_text(color="red", size=14, face="bold", hjust = 0.5))
#From this graph, in terms of proportion, we see that more males are not looking for a job change than any other genders. Also, there are more males looking for a job change as well but in terms of sample size compared against each gender, that still seems relatively low.


#We are going to visualize to see whether students currently enrolled in universities are looking for a job change based on education level.
ggplot(data = hrAnalytics, aes(x = enrolled_university, fill = education_level)) + geom_bar(position = 'dodge') + facet_wrap( ~ jobChange) + xlab("Enrolled or Not Enrolled") +
  ylab("Job Changes Count") + ggtitle("Number of Job Changes Based on University Enrollment and Education Level") + 
  geom_text(stat = 'count', aes(label = ..count..), vjust = -1, position = position_dodge(0.9)) +
  labs(fill = "Education Level") +
  theme(plot.title = element_text(color="blue", size=14, face="bold", hjust = 0.5))
#From this graph, we see that for each category of current school enrollment based on the education level, more candidates are not looking for a job change. We can also look at the proportion table below for better understanding of the data.
table(hrAnalytics[,c('enrolled_university', 'education_level', 'jobChange')]) %>% prop.table
#Based on the proportions, it looks like majority of the candidates are not looking for a job change.

#Next we'll look at the training hours for each major and see whether they are looking for a job change.
ggplot(data = hrAnalytics, aes(x = major_discipline, y = training_hours)) + geom_boxplot() + facet_wrap( ~ jobChange) + xlab("Major") +
  ylab("Training Hours") + ggtitle("Number of Job Changes Based on Training Hours and Majors") +
  theme(plot.title = element_text(color="purple", size=14, face="bold", hjust = 0.5))
#From the box plot, we can see that the average number of training hours are about the same for all the majors.

#Last visualization with city development index.
#Dividing the city development index based on quantiles for better visualization.
hrAnalytics$groupedIndex <- NA
summary(hrAnalytics$city_development_index)
hrAnalytics$groupedIndex[which(hrAnalytics$city_development_index > 0.4470 & hrAnalytics$city_development_index < 0.7450)] <- "0.4470-0.7449"
hrAnalytics$groupedIndex[which(hrAnalytics$city_development_index > 0.7449 & hrAnalytics$city_development_index < 0.8317)] <- "0.7450-0.8316"
hrAnalytics$groupedIndex[which(hrAnalytics$city_development_index > 0.8316 & hrAnalytics$city_development_index < 0.9200)] <- "0.8317-0.9199"
hrAnalytics$groupedIndex[which(hrAnalytics$city_development_index > 0.9199 & hrAnalytics$city_development_index < 0.9500)] <- "0.9200-0.9499"

ggplot(data = hrAnalytics, aes(x = groupedIndex, fill = jobChange)) + geom_bar(position = 'dodge') + xlab("Group City Development Indices") +
  ylab("Job Changes Count") + ggtitle("Number of Job Changes Based on City Development Index") +
  theme(plot.title = element_text(color="Green", size=14, face="bold", hjust = 0.5)) + 
  labs(fill = "Job Change Status")
#This is very interesting because we see that as the index increases, more candidates are lenient to not looking for a new job.
```

#Building Models
#### Creating a logistic regression model by partitioning.
```{r}
#Need to set target as a factor
hrAnalytics$target <- as.factor(hrAnalytics$target)
a <- createDataPartition(hrAnalytics$target, p = 0.8, list = FALSE) #Partioning the data by splitting 80-20.
train <- hrAnalytics[a,-c(1,2,15,16)] #Deselecting enrolee_id, city, jobChange and groupedIndex
test <- hrAnalytics[-a,-c(1,2,15,16)]
mod_fit <- train(target ~., data = train, method = "glm", family = "binomial")
vip(mod_fit)
#From the variable importance model, we see that city development index variable is significantly improtant than other variables.

#Confussion matrix to determine accuracy
pred <- predict(mod_fit, newdata = test)
confusionMatrix(data = pred, test$target)
#We can see that we achieved 77.01% accuracy from this model.
```
#### Creating a logistic regression model by cross-validation.
```{r}
fold <- trainControl(method = "repeatedcv", number = 10) #10 fold cross validation
mod_fit2 <- train(target ~., data = hrAnalytics[,-c(1,2,15,16)], method = "glm", family = "binomial", trControl = fold)
vip(mod_fit2)
pred2 <- predict(mod_fit2, newdata = test)
confusionMatrix(data = pred2, test$target)
#Although we see a slight difference in the importance of variables between the two models, the accuracy remains the same using cross validation.
```


